import React, { useState, useRef, useEffect, useCallback } from "react";
import { View, Text, TextInput, TouchableOpacity, StyleSheet, StatusBar, ScrollView, Dimensions } from "react-native";

const C = { navy: "#0c1b2e", navyLight: "#1a2d47", gold: "#c9a84c", goldLight: "#f5e6b8", goldBg: "#fdf8ec", white: "#fff", gray: "#8899aa", grayLight: "#e8ecf0", bg: "#f4f5f7" };
const SW = Dimensions.get("window").width;

// ===== DATA =====
const PROMOS = [
  { id:1, title:"Art of the Inland Empire", sub:"New exhibit \u00b7 Terminal 2 Gallery", bg:C.navyLight, accent:C.gold },
  { id:2, title:"Holiday Travel Deals", sub:"Up to 30% off at ONT shops", bg:"#6b2a3a", accent:"#f5c6d0" },
  { id:3, title:"Live Music Fridays", sub:"Jazz in Terminal 4 \u00b7 5\u20138 PM", bg:"#2a1a47", accent:"#d4b8f5" },
  { id:4, title:"New: Mobile Parking", sub:"Pre-book & pay from your phone", bg:"#1a3a2a", accent:"#b8f5d4" },
];
const HOME_FEATURES = [
  { id:"map", icon:"\ud83d\uddfa", label:"Map" },
  { id:"flights", icon:"\ud83d\udccb", label:"Flights" },
  { id:"tsa", icon:"\ud83d\udee1", label:"TSA times" },
  { id:"parking", icon:"\ud83c\udd7f\ufe0f", label:"Parking" },
  { id:"wallet", icon:"\ud83d\udcb3", label:"My wallet" },
  { id:"dutyfree", icon:"\ud83d\udecd", label:"Duty-free" },
];
const ADS = [
  { id:1, name:"Escape Lounge", tag:"Premium Lounge", desc:"Complimentary drinks, hot meals & shower suites.", icon:"\ud83d\udecb", color:"#7c6bc4" },
  { id:2, name:"Starbucks", tag:"Coffee \u00b7 Terminal 2", desc:"Mobile order ahead and skip the line.", icon:"\u2615", color:"#1e7e34" },
  { id:3, name:"El Pollo Loco", tag:"Dining \u00b7 Terminal 2", desc:"Fresh grilled chicken combos before your flight.", icon:"\ud83c\udf57", color:"#d4693e" },
  { id:4, name:"Hudson News", tag:"Retail \u00b7 Terminal 2", desc:"Travel essentials, bestselling books & gifts.", icon:"\ud83d\udecd", color:"#c45488" },
];
const MAP_POIS = [
  { id:1,name:"Gate A1",cat:"Gate",floor:2,x:18,y:15,icon:"\u2708",amenities:[] },
  { id:2,name:"Gate A2",cat:"Gate",floor:2,x:32,y:10,icon:"\u2708",amenities:[] },
  { id:3,name:"Gate A3",cat:"Gate",floor:2,x:48,y:7,icon:"\u2708",amenities:[] },
  { id:4,name:"Gate B1",cat:"Gate",floor:2,x:64,y:10,icon:"\u2708",amenities:[] },
  { id:5,name:"Gate B2",cat:"Gate",floor:2,x:78,y:15,icon:"\u2708",amenities:[] },
  { id:6,name:"Escape Lounge",cat:"Lounge",floor:3,x:35,y:35,icon:"\ud83d\udecb",rating:4.6,hours:"5 AM\u20139 PM",amenities:["Wi-Fi","Bar","Food"] },
  { id:7,name:"USO Lounge",cat:"Lounge",floor:3,x:62,y:35,icon:"\ud83d\udecb",rating:4.8,hours:"6 AM\u201310 PM",amenities:["Wi-Fi","Snacks","TV"] },
  { id:8,name:"Starbucks",cat:"Coffee",floor:2,x:25,y:45,icon:"\u2615",rating:4.2,hours:"4:30 AM\u20138 PM",amenities:["Wi-Fi","Mobile Order"] },
  { id:9,name:"McDonald's",cat:"Dining",floor:2,x:48,y:50,icon:"\ud83c\udf54",rating:3.8,hours:"5 AM\u20139 PM",amenities:["Quick Service"] },
  { id:10,name:"El Pollo Loco",cat:"Dining",floor:2,x:72,y:45,icon:"\ud83c\udf57",rating:4.0,amenities:["Quick Service"] },
  { id:11,name:"Hudson News",cat:"Retail",floor:2,x:40,y:35,icon:"\ud83d\udecd",rating:3.9,amenities:["Snacks","Magazines"] },
  { id:12,name:"Baggage A",cat:"Service",floor:1,x:30,y:30,icon:"\ud83e\uddf3",amenities:[] },
  { id:13,name:"Baggage B",cat:"Service",floor:1,x:65,y:30,icon:"\ud83e\uddf3",amenities:[] },
  { id:14,name:"Ground Transport",cat:"Service",floor:1,x:48,y:60,icon:"\ud83d\ude8c",amenities:[] },
  { id:15,name:"TSA Checkpoint A",cat:"TSA",floor:2,x:30,y:28,icon:"\ud83d\udee1",wait:12,amenities:["PreCheck","Standard"] },
  { id:16,name:"TSA Checkpoint B",cat:"TSA",floor:2,x:66,y:28,icon:"\ud83d\udee1",wait:22,amenities:["PreCheck","Standard","CLEAR"] },
];
const FLIGHTS_DATA = [
  { fn:"SW 1423",airline:"Southwest",dest:"Los Angeles (LAX)",gate:"A2",time:"10:15 AM",status:"Boarding",type:"dep" },
  { fn:"UA 892",airline:"United",dest:"San Francisco (SFO)",gate:"B1",time:"10:30 AM",status:"Boarding",type:"dep" },
  { fn:"DL 345",airline:"Delta",dest:"Atlanta (ATL)",gate:"A3",time:"11:45 AM",status:"On time",type:"dep" },
  { fn:"AA 1102",airline:"American",dest:"Dallas (DFW)",gate:"B2",time:"12:20 PM",status:"Delayed",type:"dep" },
  { fn:"SW 2281",airline:"Southwest",dest:"Denver (DEN)",gate:"A1",time:"1:05 PM",status:"On time",type:"dep" },
  { fn:"UA 1547",airline:"United",dest:"Houston (IAH)",gate:"B1",time:"2:30 PM",status:"On time",type:"dep" },
  { fn:"AA 455",airline:"American",dest:"Chicago (ORD)",gate:"B2",time:"4:00 PM",status:"Cancelled",type:"dep" },
  { fn:"SW 734",airline:"Southwest",from:"Phoenix (PHX)",gate:"A1",time:"9:45 AM",status:"Arrived",type:"arr" },
  { fn:"UA 321",airline:"United",from:"Denver (DEN)",gate:"B1",time:"10:50 AM",status:"On time",type:"arr" },
  { fn:"DL 612",airline:"Delta",from:"Minneapolis (MSP)",gate:"A2",time:"11:30 AM",status:"On time",type:"arr" },
  { fn:"AA 998",airline:"American",from:"Miami (MIA)",gate:"B2",time:"1:15 PM",status:"Delayed",type:"arr" },
];
const TSA_CPS = [
  { id:1,name:"TSA Checkpoint A",location:"Terminal 2 \u00b7 Near Gate A1",hours:"4 AM\u201310 PM",lanes:["PreCheck","Standard"],wait:12,reports:14,lastReport:"2 min ago",trend:"steady" },
  { id:2,name:"TSA Checkpoint B",location:"Terminal 2 \u00b7 Near Gate B1",hours:"4 AM\u201310 PM",lanes:["PreCheck","Standard","CLEAR"],wait:22,reports:9,lastReport:"5 min ago",trend:"increasing" },
];
const SC = {
  "Boarding":{bg:"#fdf8ec",color:"#8b6914",dot:"#c9a84c"},
  "On time":{bg:"#e6f9f0",color:"#0a7c4f",dot:"#0a7c4f"},
  "Delayed":{bg:"#fce8e8",color:"#c0392b",dot:"#c0392b"},
  "Cancelled":{bg:"#f5f0f0",color:"#888",dot:"#888"},
  "Arrived":{bg:"#e6f1fb",color:"#185fa5",dot:"#185fa5"},
};
const CAT_COLORS = {Gate:C.gold,Lounge:"#9b7fd4",Coffee:"#c8950f",Dining:"#d4693e",Retail:"#c45488",Service:"#5a9fd4",TSA:"#e05555"};
function wc(w){return w<=15?"#0a7c4f":w<=25?"#b8860b":"#c0392b"}
function wb(w){return w<=15?"#e6f9f0":w<=25?"#fff8e6":"#fce8e8"}
function wl(w){return w<=15?"Short wait":w<=25?"Moderate wait":"Long wait"}

// ===== BOTTOM TAB =====
function BT({active,nav}){
  var tabs=[{id:"home",icon:"\ud83c\udfe0",label:"Home"},{id:"map",icon:"\ud83d\uddfa",label:"Map"},{id:"flights",icon:"\u2708",label:"My flight"},{id:"profile",icon:"\ud83d\udc64",label:"Profile"}];
  return <View style={bt.bar}>{tabs.map(function(t){return <TouchableOpacity key={t.id} style={bt.tab} onPress={function(){nav(t.id)}}><Text style={{fontSize:20}}>{t.icon}</Text><Text style={[bt.label,active===t.id&&{color:C.gold,fontWeight:"700"}]}>{t.label}</Text></TouchableOpacity>})}</View>;
}
var bt=StyleSheet.create({bar:{flexDirection:"row",justifyContent:"space-around",paddingVertical:10,paddingBottom:20,backgroundColor:C.white,borderTopWidth:1,borderTopColor:C.grayLight},tab:{alignItems:"center",gap:2},label:{fontSize:10,fontWeight:"500",color:C.gray}});

// ===== WELCOME =====
function Welcome({done}){
  var[s,setS]=useState("welcome"),[em,setEm]=useState(""),[nm,setNm]=useState(""),[pw,setPw]=useState("");
  if(s==="signup")return <View style={ws.formBg}><StatusBar barStyle="dark-content"/><View style={ws.fi}><TouchableOpacity onPress={function(){setS("welcome")}}><Text style={ws.back}>{"\u2190 Back"}</Text></TouchableOpacity><Text style={ws.ft}>Create account</Text><Text style={ws.fs}>Start navigating ONT like a pro.</Text><Text style={ws.lb}>Full name</Text><TextInput style={ws.inp} placeholder="e.g. Alex Rivera" value={nm} onChangeText={setNm}/><Text style={ws.lb}>Email</Text><TextInput style={ws.inp} placeholder="you@email.com" keyboardType="email-address" value={em} onChangeText={setEm} autoCapitalize="none"/><Text style={ws.lb}>Password</Text><TextInput style={ws.inp} placeholder="6+ characters" secureTextEntry value={pw} onChangeText={setPw}/><TouchableOpacity style={ws.pb} onPress={function(){setS("ready")}}><Text style={ws.pbt}>Create account</Text></TouchableOpacity><Text style={ws.sw}>Already have an account? <Text style={ws.sl} onPress={function(){setS("login")}}>Log in</Text></Text></View></View>;
  if(s==="login")return <View style={ws.formBg}><StatusBar barStyle="dark-content"/><View style={ws.fi}><TouchableOpacity onPress={function(){setS("welcome")}}><Text style={ws.back}>{"\u2190 Back"}</Text></TouchableOpacity><Text style={ws.ft}>Welcome back</Text><Text style={ws.fs}>Log in to pick up where you left off.</Text><Text style={ws.lb}>Email</Text><TextInput style={ws.inp} placeholder="you@email.com" keyboardType="email-address" value={em} onChangeText={setEm} autoCapitalize="none"/><Text style={ws.lb}>Password</Text><TextInput style={ws.inp} placeholder="Your password" secureTextEntry value={pw} onChangeText={setPw}/><TouchableOpacity style={ws.pb} onPress={function(){setS("ready")}}><Text style={ws.pbt}>Log in</Text></TouchableOpacity><Text style={ws.sw}>Don't have an account? <Text style={ws.sl} onPress={function(){setS("signup")}}>Sign up</Text></Text></View></View>;
  if(s==="ready")return <View style={ws.hero}><StatusBar barStyle="light-content"/><View style={ws.chk}><Text style={{fontSize:36,color:C.gold}}>{"\u2713"}</Text></View><Text style={ws.rt}>You're all set</Text><Text style={ws.rs}>Your ONT Navigator is ready.</Text><TouchableOpacity style={ws.rb} onPress={done}><Text style={ws.rbt}>Open the app</Text></TouchableOpacity></View>;
  return <View style={ws.hero}><StatusBar barStyle="light-content"/><View style={ws.badge}><Text style={ws.badgeT}>ONTARIO INTERNATIONAL AIRPORT</Text></View><View style={ws.logo}><Text style={{fontSize:28,color:C.gold}}>{"\u2708"}</Text></View><Text style={ws.title}>ONT Navigator</Text><Text style={ws.tag}>{"Your gate. Your lounge. Your flight.\nAll in one tap."}</Text><View style={ws.bg}><TouchableOpacity style={ws.sb} onPress={function(){setS("signup")}}><Text style={ws.sbt}>Get started</Text></TouchableOpacity><TouchableOpacity style={ws.lb2} onPress={function(){setS("login")}}><Text style={ws.lbt}>I already have an account</Text></TouchableOpacity><TouchableOpacity onPress={done}><Text style={ws.gl}>{"Continue as guest \u2192"}</Text></TouchableOpacity></View></View>;
}
var ws=StyleSheet.create({hero:{flex:1,alignItems:"center",justifyContent:"center",padding:32,backgroundColor:C.navy},badge:{backgroundColor:"rgba(201,168,76,0.12)",borderRadius:30,paddingVertical:6,paddingHorizontal:16,marginBottom:40},badgeT:{fontSize:11,fontWeight:"600",color:C.gold,letterSpacing:1.5},logo:{width:72,height:72,borderRadius:20,backgroundColor:"rgba(201,168,76,0.1)",alignItems:"center",justifyContent:"center",marginBottom:20,borderWidth:1,borderColor:"rgba(201,168,76,0.2)"},title:{fontSize:34,fontWeight:"800",color:C.white,marginBottom:12},tag:{fontSize:16,color:"rgba(255,255,255,0.75)",textAlign:"center",lineHeight:24,marginBottom:48},bg:{width:"100%",maxWidth:320,alignItems:"center"},sb:{width:"100%",paddingVertical:15,borderRadius:14,backgroundColor:C.gold,alignItems:"center",marginBottom:10},sbt:{fontSize:16,fontWeight:"700",color:C.navy},lb2:{width:"100%",paddingVertical:15,borderRadius:14,borderWidth:2,borderColor:"rgba(201,168,76,0.3)",alignItems:"center"},lbt:{fontSize:15,fontWeight:"600",color:C.gold},gl:{fontSize:14,color:"rgba(255,255,255,0.5)",fontWeight:"500",marginTop:20},formBg:{flex:1,backgroundColor:C.white,justifyContent:"center"},fi:{padding:32},back:{fontSize:15,color:C.gold,fontWeight:"600",marginBottom:24},ft:{fontSize:24,fontWeight:"700",color:C.navy,marginBottom:4},fs:{fontSize:14,color:C.gray,marginBottom:28},lb:{fontSize:13,fontWeight:"600",color:"#444",marginBottom:6,marginTop:16},inp:{width:"100%",paddingVertical:12,paddingHorizontal:14,borderRadius:12,borderWidth:1.5,borderColor:C.grayLight,fontSize:15,backgroundColor:"#fafafa"},pb:{width:"100%",paddingVertical:14,borderRadius:14,backgroundColor:C.navy,alignItems:"center",marginTop:24},pbt:{fontSize:16,fontWeight:"700",color:C.gold},sw:{textAlign:"center",marginTop:16,fontSize:13,color:C.gray},sl:{color:C.gold,fontWeight:"600"},chk:{width:80,height:80,borderRadius:40,backgroundColor:"rgba(201,168,76,0.12)",alignItems:"center",justifyContent:"center",marginBottom:20},rt:{fontSize:26,fontWeight:"700",color:C.white,marginBottom:8},rs:{fontSize:15,color:"rgba(255,255,255,0.75)",textAlign:"center",marginBottom:32},rb:{backgroundColor:C.gold,paddingVertical:14,paddingHorizontal:48,borderRadius:14},rbt:{fontSize:16,fontWeight:"700",color:C.navy}});

// ===== HOME =====
function Home({nav}){
  var[ap,setAp]=useState(0),pr=useRef(null);
  useEffect(function(){var t=setInterval(function(){setAp(function(p){var n=(p+1)%PROMOS.length;pr.current&&pr.current.scrollTo({x:n*(SW-40),animated:true});return n})},4000);return function(){clearInterval(t)}},[]);
  return <View style={hs.c}><StatusBar barStyle="light-content"/>
    <View style={hs.hd}><View><Text style={hs.hdSub}>ONTARIO INTERNATIONAL</Text><Text style={hs.hdTitle}>{"Good morning \u2708"}</Text></View><TouchableOpacity style={hs.prof} onPress={function(){nav("profile")}}><Text style={{fontSize:16}}>{"\ud83d\udc64"}</Text></TouchableOpacity></View>
    <ScrollView style={{flex:1}} showsVerticalScrollIndicator={false}>
      <View style={hs.srchW}><Text style={{fontSize:14,color:C.gray}}>{"\ud83d\udd0d"}</Text><TextInput style={hs.srchI} placeholder="Search gates, food, lounges..." placeholderTextColor={C.gray}/></View>
      <View style={{marginTop:20}}><View style={hs.secH}><Text style={hs.secT}>What's happening at ONT</Text><Text style={hs.secL}>See all</Text></View>
        <ScrollView ref={pr} horizontal pagingEnabled showsHorizontalScrollIndicator={false} contentContainerStyle={{paddingHorizontal:20}} decelerationRate="fast" snapToInterval={SW-40} snapToAlignment="start" onMomentumScrollEnd={function(e){var i=Math.round(e.nativeEvent.contentOffset.x/(SW-40));if(i>=0&&i<PROMOS.length)setAp(i)}}>
          {PROMOS.map(function(p){return <View key={p.id} style={[hs.pc,{backgroundColor:p.bg,width:SW-40}]}><Text style={hs.pt}>{p.title}</Text><Text style={[hs.ps,{color:p.accent}]}>{p.sub}</Text><View style={hs.pbtn}><Text style={hs.pbtnt}>Learn more</Text></View></View>})}
        </ScrollView>
        <View style={hs.dots}>{PROMOS.map(function(_,i){return <View key={i} style={[hs.dot,{width:i===ap?18:6,backgroundColor:i===ap?C.gold:C.grayLight}]}/>})}</View>
      </View>
      <View style={hs.sec}><Text style={hs.secT}>Quick access</Text><View style={hs.fg}>{HOME_FEATURES.map(function(f){return <TouchableOpacity key={f.id} style={hs.fi} onPress={function(){nav(f.id)}}><View style={hs.fic}><Text style={{fontSize:22}}>{f.icon}</Text></View><Text style={hs.fl}>{f.label}</Text></TouchableOpacity>})}</View></View>
      <View style={[hs.sec,{paddingBottom:30}]}><View style={hs.secH}><Text style={hs.secT}>Explore ONT businesses</Text><Text style={hs.secL}>View all</Text></View>
        {ADS.map(function(a){return <View key={a.id} style={hs.ac}><View style={{flexDirection:"row",gap:14}}><View style={[hs.ai,{backgroundColor:a.color+"18"}]}><Text style={{fontSize:26}}>{a.icon}</Text></View><View style={{flex:1}}><Text style={hs.an}>{a.name}</Text><Text style={hs.at}>{a.tag}</Text><Text style={hs.ad}>{a.desc}</Text></View></View><View style={{flexDirection:"row",gap:8,marginTop:12}}><TouchableOpacity style={hs.abo}><Text style={hs.abot}>View details</Text></TouchableOpacity><TouchableOpacity style={hs.abf} onPress={function(){nav("map")}}><Text style={hs.abft}>Navigate</Text></TouchableOpacity></View></View>})}
      </View>
    </ScrollView>
    <BT active="home" nav={nav}/>
  </View>;
}
var hs=StyleSheet.create({c:{flex:1,backgroundColor:C.bg},hd:{backgroundColor:C.navy,paddingHorizontal:20,paddingTop:50,paddingBottom:24,flexDirection:"row",justifyContent:"space-between",alignItems:"center",borderBottomLeftRadius:24,borderBottomRightRadius:24},hdSub:{fontSize:11,color:C.gold,fontWeight:"600",letterSpacing:1.5,marginBottom:4},hdTitle:{fontSize:24,fontWeight:"800",color:C.white},prof:{width:40,height:40,borderRadius:20,backgroundColor:"rgba(255,255,255,0.1)",alignItems:"center",justifyContent:"center",borderWidth:1.5,borderColor:"rgba(201,168,76,0.3)"},srchW:{marginHorizontal:20,marginTop:-18,backgroundColor:C.white,borderRadius:16,paddingVertical:12,paddingHorizontal:16,flexDirection:"row",alignItems:"center",gap:10,shadowColor:"#000",shadowOpacity:0.06,shadowRadius:12,elevation:4,zIndex:5},srchI:{flex:1,fontSize:15,color:C.navy},secH:{flexDirection:"row",justifyContent:"space-between",alignItems:"center",marginBottom:12},secT:{fontSize:16,fontWeight:"700",color:C.navy},secL:{fontSize:12,color:C.gold,fontWeight:"600"},sec:{marginHorizontal:20,marginTop:24},pc:{height:140,borderRadius:18,padding:18,justifyContent:"center"},pt:{fontSize:18,fontWeight:"800",color:C.white,marginBottom:6,lineHeight:24},ps:{fontSize:12,fontWeight:"600"},pbtn:{marginTop:10,backgroundColor:"rgba(255,255,255,0.15)",alignSelf:"flex-start",paddingVertical:5,paddingHorizontal:14,borderRadius:20},pbtnt:{fontSize:11,fontWeight:"600",color:C.white},dots:{flexDirection:"row",justifyContent:"center",gap:6,marginTop:10},dot:{height:6,borderRadius:3},fg:{flexDirection:"row",flexWrap:"wrap",gap:12,marginTop:2},fi:{width:(SW-64)/3,alignItems:"center",gap:8,paddingVertical:16,backgroundColor:C.white,borderRadius:16,shadowColor:"#000",shadowOpacity:0.03,shadowRadius:6,elevation:1},fic:{width:48,height:48,borderRadius:14,backgroundColor:C.goldBg,alignItems:"center",justifyContent:"center"},fl:{fontSize:12,fontWeight:"600",color:C.navy,textAlign:"center"},ac:{backgroundColor:C.white,borderRadius:18,padding:16,marginBottom:12,shadowColor:"#000",shadowOpacity:0.03,shadowRadius:6,elevation:1},ai:{width:56,height:56,borderRadius:14,alignItems:"center",justifyContent:"center"},an:{fontSize:15,fontWeight:"700",color:C.navy},at:{fontSize:11,color:C.gold,fontWeight:"600",marginTop:1},ad:{fontSize:12,color:C.gray,marginTop:4,lineHeight:18},abo:{flex:1,paddingVertical:8,borderRadius:10,borderWidth:1.5,borderColor:C.grayLight,alignItems:"center"},abot:{fontSize:12,fontWeight:"600",color:C.navy},abf:{flex:1,paddingVertical:8,borderRadius:10,backgroundColor:C.navy,alignItems:"center"},abft:{fontSize:12,fontWeight:"700",color:C.gold}});

// ===== MAP =====
function MapScreen({nav}){
  var[fl,setFl]=useState(2),[sr,setSr]=useState(""),[sel,setSel]=useState(null),[rt,setRt]=useState(null),[af,setAf]=useState("All");
  var cm={Gates:"Gate",Lounges:"Lounge",Dining:"Dining",Coffee:"Coffee",TSA:"TSA"};
  var fps=MAP_POIS.filter(function(p){if(p.floor!==fl)return false;if(sr.length>0)return p.name.toLowerCase().includes(sr.toLowerCase())||p.cat.toLowerCase().includes(sr.toLowerCase());if(af!=="All")return p.cat===cm[af];return true});
  var srs=sr.length>0?MAP_POIS.filter(function(p){return p.name.toLowerCase().includes(sr.toLowerCase())||p.cat.toLowerCase().includes(sr.toLowerCase())}):[];
  return <View style={ms.c}><StatusBar barStyle="light-content"/>
    <View style={ms.hd}>
      <View style={{flexDirection:"row",justifyContent:"space-between",alignItems:"center",marginBottom:10,paddingTop:4}}>
        <TouchableOpacity style={ms.bb} onPress={function(){nav("home")}}><Text style={{fontSize:16,color:C.white}}>{"\u2190"}</Text></TouchableOpacity>
        <Text style={{fontSize:17,fontWeight:"700",color:C.white}}>Map</Text><View style={{width:36}}/>
      </View>
      <View style={ms.sw}><Text style={{fontSize:14,color:"rgba(255,255,255,0.4)"}}>{"\ud83d\udd0d"}</Text><TextInput style={ms.si} placeholder="Search gates, food, lounges..." placeholderTextColor="rgba(255,255,255,0.3)" value={sr} onChangeText={function(v){setSr(v);setAf("All");setSel(null)}}/>{sr?<TouchableOpacity onPress={function(){setSr("")}}><Text style={{fontSize:14,color:"rgba(255,255,255,0.4)"}}>{"\u2715"}</Text></TouchableOpacity>:null}</View>
      <ScrollView horizontal showsHorizontalScrollIndicator={false} style={{marginTop:10}}>{["All","Gates","Dining","Coffee","Lounges","TSA"].map(function(f){return <TouchableOpacity key={f} style={[ms.fp,af===f&&ms.fpa]} onPress={function(){setAf(f);setSr("");setSel(null)}}><Text style={[ms.ft,af===f&&ms.fta]}>{f}</Text></TouchableOpacity>})}</ScrollView>
      {sr.length>0&&srs.length>0&&<View style={ms.dd}>{srs.slice(0,5).map(function(p){return <TouchableOpacity key={p.id} style={ms.di} onPress={function(){setSel(p);setSr("");if(p.floor!==fl)setFl(p.floor)}}><View style={{width:28,height:28,borderRadius:14,backgroundColor:CAT_COLORS[p.cat]||C.gray,alignItems:"center",justifyContent:"center"}}><Text style={{fontSize:12,color:"#fff"}}>{p.icon}</Text></View><View><Text style={{fontWeight:"600",fontSize:14,color:C.navy}}>{p.name}</Text><Text style={{fontSize:12,color:C.gray}}>{p.cat} {"\u00b7"} Level {p.floor}</Text></View></TouchableOpacity>})}</View>}
    </View>
    <View style={ms.ma}>
      <View style={ms.tb}><Text style={ms.tl}>{"ONT Terminal \u00b7 "}{fl===1?"Arrivals":fl===2?"Departures":"Lounges"}</Text></View>
      <View style={ms.pg}>{fps.map(function(p){return <TouchableOpacity key={p.id} style={ms.pi} onPress={function(){setSel(p)}}><View style={[ms.pd,{backgroundColor:p.cat==="TSA"&&p.wait?(p.wait<=15?"#0a7c4f":p.wait<=25?"#b8860b":"#c0392b"):CAT_COLORS[p.cat]||C.gray}]}>{p.cat==="TSA"&&p.wait?<Text style={{fontSize:10,fontWeight:"800",color:"#fff"}}>{p.wait}m</Text>:<Text style={{fontSize:14,color:"#fff"}}>{p.icon}</Text>}</View><Text style={ms.pn} numberOfLines={1}>{p.name}</Text></TouchableOpacity>})}{fps.length===0&&<Text style={{color:C.gray,fontSize:14,padding:20}}>No results</Text>}</View>
      <View style={ms.fls}>{[{id:1,l:"1",s:"Arr"},{id:2,l:"2",s:"Dep"},{id:3,l:"3",s:"Lnge"}].map(function(f){return <TouchableOpacity key={f.id} style={[ms.fb,fl===f.id&&ms.fba]} onPress={function(){setFl(f.id);setSel(null);setAf("All")}}><Text style={{fontSize:14,fontWeight:"700",color:fl===f.id?C.navy:C.gray}}>{f.l}</Text><Text style={{fontSize:8,fontWeight:"600",color:fl===f.id?C.gold:"#bbb"}}>{f.s}</Text></TouchableOpacity>})}</View>
      {sel&&!rt&&<View style={ms.card}><View style={ms.ch}/><View style={{flexDirection:"row",justifyContent:"space-between",alignItems:"flex-start"}}><View style={{flex:1}}><Text style={{fontSize:18,fontWeight:"700",color:C.navy}}>{sel.name}</Text><Text style={{fontSize:13,color:C.gray,marginTop:2}}>{sel.cat} {"\u00b7"} Level {sel.floor}</Text></View><View style={{width:46,height:46,borderRadius:14,backgroundColor:(CAT_COLORS[sel.cat]||C.gray)+"15",alignItems:"center",justifyContent:"center"}}><Text style={{fontSize:22}}>{sel.icon}</Text></View></View>
        {sel.rating?<View style={{flexDirection:"row",alignItems:"center",gap:6,marginTop:10}}><Text style={{color:C.gold}}>{"\u2605"}</Text><Text style={{fontWeight:"600",color:C.navy}}>{sel.rating}</Text>{sel.hours?<Text style={{color:C.gray,fontSize:12}}>{"\u00b7 "}{sel.hours}</Text>:null}</View>:null}
        {sel.cat==="TSA"&&sel.wait?<View style={{flexDirection:"row",alignItems:"center",gap:10,padding:10,borderRadius:12,backgroundColor:wb(sel.wait),marginTop:10}}><Text style={{fontSize:22,fontWeight:"800",color:wc(sel.wait)}}>{sel.wait}</Text><View><Text style={{fontSize:13,fontWeight:"700",color:wc(sel.wait)}}>{wl(sel.wait)}</Text><Text style={{fontSize:11,color:C.gray}}>min estimated</Text></View></View>:null}
        {sel.amenities&&sel.amenities.length>0?<View style={{flexDirection:"row",flexWrap:"wrap",gap:6,marginTop:10}}>{sel.amenities.map(function(a){return <View key={a} style={{paddingVertical:4,paddingHorizontal:10,borderRadius:20,backgroundColor:C.goldBg}}><Text style={{fontSize:11,fontWeight:"500",color:"#8b6914"}}>{a}</Text></View>})}</View>:null}
        <TouchableOpacity style={ms.nb} onPress={function(){setRt(sel);setSel(null)}}><Text style={{fontSize:15,fontWeight:"700",color:C.gold}}>Navigate here</Text></TouchableOpacity>
      </View>}
      {rt&&<View style={ms.rb}><View style={{flexDirection:"row",alignItems:"center",gap:10}}><View style={{width:32,height:32,borderRadius:10,backgroundColor:"rgba(201,168,76,0.2)",alignItems:"center",justifyContent:"center"}}><Text style={{fontSize:14}}>{rt.icon}</Text></View><View><Text style={{fontSize:14,fontWeight:"700",color:C.white}}>Navigating to {rt.name}</Text><Text style={{fontSize:11,color:"rgba(255,255,255,0.5)"}}>Level {rt.floor}</Text></View></View><TouchableOpacity style={ms.re} onPress={function(){setRt(null)}}><Text style={{color:C.gold,fontWeight:"700",fontSize:13}}>End</Text></TouchableOpacity></View>}
    </View>
    <BT active="map" nav={nav}/>
  </View>;
}
var ms=StyleSheet.create({c:{flex:1,backgroundColor:"#eae8e1"},hd:{backgroundColor:C.navy,paddingHorizontal:16,paddingTop:10,paddingBottom:12,borderBottomLeftRadius:20,borderBottomRightRadius:20,zIndex:20},bb:{width:36,height:36,borderRadius:10,backgroundColor:"rgba(255,255,255,0.08)",alignItems:"center",justifyContent:"center"},sw:{flexDirection:"row",alignItems:"center",gap:10,backgroundColor:"rgba(255,255,255,0.08)",borderRadius:12,paddingVertical:9,paddingHorizontal:14},si:{flex:1,fontSize:14,color:C.white},fp:{paddingVertical:5,paddingHorizontal:12,borderRadius:20,borderWidth:1,borderColor:"rgba(255,255,255,0.12)",backgroundColor:"rgba(255,255,255,0.05)",marginRight:6},fpa:{backgroundColor:C.gold,borderColor:C.gold},ft:{fontSize:12,fontWeight:"500",color:"rgba(255,255,255,0.5)"},fta:{color:C.navy,fontWeight:"700"},dd:{position:"absolute",left:16,right:16,top:"100%",backgroundColor:C.white,borderRadius:14,marginTop:6,zIndex:30,elevation:8},di:{padding:10,flexDirection:"row",alignItems:"center",gap:10,borderBottomWidth:1,borderBottomColor:"#f5f5f5"},ma:{flex:1,alignItems:"center",justifyContent:"center"},tb:{width:"92%",height:"90%",position:"absolute",left:"4%",top:"3%",borderRadius:18,borderWidth:1.5,borderColor:"rgba(12,27,46,0.12)",backgroundColor:"#f2f1ec",alignItems:"center",justifyContent:"center"},tl:{fontSize:12,color:"rgba(12,27,46,0.12)",fontWeight:"700",letterSpacing:2.5,textTransform:"uppercase"},pg:{flexDirection:"row",flexWrap:"wrap",justifyContent:"center",padding:8,gap:8,position:"absolute",top:"10%",left:10,right:10},pi:{alignItems:"center",width:72,marginBottom:4},pd:{width:40,height:40,borderRadius:20,alignItems:"center",justifyContent:"center",borderWidth:2.5,borderColor:"#fff"},pn:{fontSize:10,fontWeight:"600",color:C.navy,marginTop:3,textAlign:"center"},fls:{position:"absolute",right:12,top:"40%",backgroundColor:C.white,borderRadius:14,padding:4,elevation:4},fb:{width:44,height:44,borderRadius:10,alignItems:"center",justifyContent:"center"},fba:{backgroundColor:C.goldBg},card:{position:"absolute",bottom:0,left:0,right:0,backgroundColor:C.white,borderTopLeftRadius:22,borderTopRightRadius:22,padding:20,paddingBottom:28,zIndex:25,elevation:8},ch:{width:36,height:4,borderRadius:2,backgroundColor:C.grayLight,alignSelf:"center",marginBottom:14},nb:{paddingVertical:12,backgroundColor:C.navy,borderRadius:14,alignItems:"center",marginTop:14},rb:{position:"absolute",bottom:12,left:12,right:12,zIndex:25,backgroundColor:C.navy,borderRadius:18,padding:14,paddingHorizontal:16,flexDirection:"row",justifyContent:"space-between",alignItems:"center",elevation:6},re:{paddingVertical:8,paddingHorizontal:18,borderRadius:10,backgroundColor:"rgba(201,168,76,0.15)"}});

// ===== FLIGHTS =====
function Flights({nav}){
  var[tab,setTab]=useState("dep"),[sr,setSr]=useState(""),[sf,setSf]=useState(null),[mf,setMf]=useState(null);
  var fls=FLIGHTS_DATA.filter(function(f){return f.type===tab&&(sr.length===0||f.fn.toLowerCase().includes(sr.toLowerCase())||f.airline.toLowerCase().includes(sr.toLowerCase())||(f.dest||"").toLowerCase().includes(sr.toLowerCase())||(f.from||"").toLowerCase().includes(sr.toLowerCase()))});
  var gs=[{l:"Boarding now",d:fls.filter(function(f){return f.status==="Boarding"&&f.fn!==mf})},{l:tab==="dep"?"Upcoming":"Arriving",d:fls.filter(function(f){return f.status==="On time"&&f.fn!==mf})},{l:"Delayed",d:fls.filter(function(f){return f.status==="Delayed"&&f.fn!==mf})},{l:"Other",d:fls.filter(function(f){return!["Boarding","On time","Delayed"].includes(f.status)&&f.fn!==mf})}].filter(function(g){return g.d.length>0});
  var pin=mf?FLIGHTS_DATA.find(function(f){return f.fn===mf}):null;
  function FR({f}){var sc=SC[f.status]||SC["On time"];return <TouchableOpacity style={fs.row} onPress={function(){setSf(f)}}><View style={{flexDirection:"row",justifyContent:"space-between",alignItems:"center"}}><View style={{flexDirection:"row",alignItems:"center",gap:10}}><View style={fs.ai}><Text style={{fontSize:14,fontWeight:"700",color:C.gold}}>{f.airline[0]}</Text></View><View><Text style={{fontSize:15,fontWeight:"700",color:C.navy}}>{f.fn}</Text><Text style={{fontSize:12,color:C.gray}}>{f.airline}</Text></View></View><View style={[fs.badge,{backgroundColor:sc.bg}]}><View style={{width:6,height:6,borderRadius:3,backgroundColor:sc.dot}}/><Text style={{fontSize:11,fontWeight:"600",color:sc.color}}>{f.status}</Text></View></View><View style={fs.meta}><View><Text style={fs.ml}>{tab==="dep"?"To":"From"}</Text><Text style={fs.mv}>{f.dest||f.from}</Text></View><View><Text style={fs.ml}>Gate</Text><Text style={fs.mv}>{f.gate}</Text></View><View><Text style={fs.ml}>Time</Text><Text style={fs.mv}>{f.time}</Text></View></View></TouchableOpacity>}
  return <View style={fs.c}><StatusBar barStyle="light-content"/>
    <View style={fs.hd}><View style={{flexDirection:"row",justifyContent:"space-between",alignItems:"center",marginBottom:4,paddingTop:4}}><TouchableOpacity style={fs.bb} onPress={function(){nav("home")}}><Text style={{fontSize:16,color:C.white}}>{"\u2190"}</Text></TouchableOpacity><Text style={{fontSize:17,fontWeight:"700",color:C.white}}>Flight scanner</Text><View style={{width:36}}/></View>
      <Text style={{fontSize:12,color:C.gold,fontWeight:"600",letterSpacing:1,textAlign:"center",marginBottom:12}}>{"KONT \u00b7 TODAY"}</Text>
      <View style={fs.tr}><TouchableOpacity style={[fs.tb,tab==="dep"&&fs.tba]} onPress={function(){setTab("dep");setSr("")}}><Text style={[fs.tt,tab==="dep"&&fs.tta]}>Departures</Text></TouchableOpacity><TouchableOpacity style={[fs.tb,tab==="arr"&&fs.tba]} onPress={function(){setTab("arr");setSr("")}}><Text style={[fs.tt,tab==="arr"&&fs.tta]}>Arrivals</Text></TouchableOpacity></View>
      <View style={fs.sw}><Text style={{fontSize:14,color:"rgba(255,255,255,0.4)"}}>{"\ud83d\udd0d"}</Text><TextInput style={fs.si} placeholder="Search flight, airline, city..." placeholderTextColor="rgba(255,255,255,0.3)" value={sr} onChangeText={setSr}/></View>
    </View>
    <ScrollView style={{flex:1,paddingHorizontal:16}}>
      {pin&&!sr?<View style={[fs.row,{borderLeftWidth:3,borderLeftColor:C.gold,backgroundColor:C.goldBg,marginTop:14}]}><View style={{flexDirection:"row",justifyContent:"space-between",alignItems:"center"}}><View style={{flexDirection:"row",alignItems:"center",gap:10}}><View style={fs.ai}><Text style={{fontSize:14,fontWeight:"700",color:C.gold}}>{pin.airline[0]}</Text></View><View><View style={{flexDirection:"row",alignItems:"center",gap:6}}><Text style={{fontSize:15,fontWeight:"700",color:C.navy}}>{pin.fn}</Text><View style={{backgroundColor:C.white,paddingHorizontal:6,paddingVertical:2,borderRadius:6}}><Text style={{fontSize:9,fontWeight:"700",color:C.gold}}>MY FLIGHT</Text></View></View><Text style={{fontSize:12,color:C.gray}}>{pin.airline}</Text></View></View><View style={[fs.badge,{backgroundColor:(SC[pin.status]||SC["On time"]).bg}]}><View style={{width:6,height:6,borderRadius:3,backgroundColor:(SC[pin.status]||SC["On time"]).dot}}/><Text style={{fontSize:11,fontWeight:"600",color:(SC[pin.status]||SC["On time"]).color}}>{pin.status}</Text></View></View><View style={fs.meta}><View><Text style={fs.ml}>{pin.type==="dep"?"To":"From"}</Text><Text style={fs.mv}>{pin.dest||pin.from}</Text></View><View><Text style={fs.ml}>Gate</Text><Text style={fs.mv}>{pin.gate}</Text></View><View><Text style={fs.ml}>Time</Text><Text style={fs.mv}>{pin.time}</Text></View></View><View style={{flexDirection:"row",gap:8,marginTop:10}}><TouchableOpacity style={{flex:1,paddingVertical:7,borderRadius:8,backgroundColor:C.navy,alignItems:"center"}}><Text style={{fontSize:11,fontWeight:"700",color:C.gold}}>Navigate to gate</Text></TouchableOpacity><TouchableOpacity style={{flex:1,paddingVertical:7,borderRadius:8,borderWidth:1,borderColor:C.grayLight,alignItems:"center"}} onPress={function(){setMf(null)}}><Text style={{fontSize:11,fontWeight:"600",color:C.navy}}>Remove</Text></TouchableOpacity></View></View>:null}
      {gs.map(function(g){return <View key={g.l}><Text style={fs.sl}>{g.l}</Text>{g.d.map(function(f){return <FR key={f.fn} f={f}/>})}</View>})}<View style={{height:20}}/>
    </ScrollView>
    {sf?<TouchableOpacity style={fs.ov} activeOpacity={1} onPress={function(){setSf(null)}}><View style={fs.sh}><View style={fs.handle}/><Text style={{fontSize:22,fontWeight:"800",color:C.navy}}>{sf.fn}</Text><Text style={{fontSize:13,color:C.gray,marginBottom:16}}>{sf.airline}</Text><View style={{flexDirection:"row",gap:8,marginBottom:16}}><View style={fs.db}><Text style={fs.dl}>{tab==="dep"?"Destination":"Origin"}</Text><Text style={fs.dv}>{sf.dest||sf.from}</Text></View><View style={fs.db}><Text style={fs.dl}>Gate</Text><Text style={[fs.dv,{fontSize:20}]}>{sf.gate}</Text></View></View><View style={{flexDirection:"row",gap:8,marginBottom:16}}><View style={fs.db}><Text style={fs.dl}>{tab==="dep"?"Departs":"Arrives"}</Text><Text style={[fs.dv,{fontSize:20}]}>{sf.time}</Text></View><View style={fs.db}><Text style={fs.dl}>Terminal</Text><Text style={[fs.dv,{fontSize:20}]}>2</Text></View></View><View style={{flexDirection:"row",gap:8}}><TouchableOpacity style={{flex:1,paddingVertical:12,borderRadius:12,backgroundColor:C.navy,alignItems:"center"}} onPress={function(){setMf(sf.fn);setSf(null)}}><Text style={{fontSize:14,fontWeight:"700",color:C.gold}}>{mf===sf.fn?"Remove my flight":"Set as my flight"}</Text></TouchableOpacity><TouchableOpacity style={{flex:1,paddingVertical:12,borderRadius:12,borderWidth:1.5,borderColor:C.grayLight,alignItems:"center"}}><Text style={{fontSize:14,fontWeight:"600",color:C.navy}}>Navigate to gate</Text></TouchableOpacity></View></View></TouchableOpacity>:null}
    <BT active="flights" nav={nav}/>
  </View>;
}
var fs=StyleSheet.create({c:{flex:1,backgroundColor:C.bg},hd:{backgroundColor:C.navy,padding:16,paddingTop:10,borderBottomLeftRadius:20,borderBottomRightRadius:20,zIndex:10},bb:{width:36,height:36,borderRadius:10,backgroundColor:"rgba(255,255,255,0.08)",alignItems:"center",justifyContent:"center"},tr:{flexDirection:"row",gap:4,backgroundColor:"rgba(255,255,255,0.06)",borderRadius:12,padding:3,marginBottom:10},tb:{flex:1,paddingVertical:8,borderRadius:10,alignItems:"center"},tba:{backgroundColor:C.gold},tt:{fontSize:13,fontWeight:"600",color:"rgba(255,255,255,0.4)"},tta:{color:C.navy,fontWeight:"700"},sw:{flexDirection:"row",alignItems:"center",gap:10,backgroundColor:"rgba(255,255,255,0.08)",borderRadius:12,paddingVertical:9,paddingHorizontal:14},si:{flex:1,fontSize:14,color:C.white},row:{backgroundColor:C.white,borderRadius:14,padding:14,marginBottom:8,shadowColor:"#000",shadowOpacity:0.03,shadowRadius:6,elevation:1},ai:{width:32,height:32,borderRadius:8,backgroundColor:C.navyLight,alignItems:"center",justifyContent:"center"},badge:{flexDirection:"row",alignItems:"center",gap:5,paddingVertical:4,paddingHorizontal:10,borderRadius:8},meta:{flexDirection:"row",justifyContent:"space-between",marginTop:10,paddingTop:10,borderTopWidth:1,borderTopColor:C.grayLight},ml:{fontSize:10,color:C.gray,fontWeight:"500"},mv:{fontSize:13,fontWeight:"600",color:C.navy},sl:{fontSize:11,fontWeight:"700",color:C.gray,textTransform:"uppercase",letterSpacing:1.2,marginTop:18,marginBottom:8},ov:{position:"absolute",top:0,left:0,right:0,bottom:0,backgroundColor:"rgba(12,27,46,0.5)",justifyContent:"flex-end",zIndex:50},sh:{backgroundColor:C.white,borderTopLeftRadius:22,borderTopRightRadius:22,padding:20,paddingBottom:28},handle:{width:36,height:4,borderRadius:2,backgroundColor:C.grayLight,alignSelf:"center",marginBottom:14},db:{flex:1,backgroundColor:C.bg,borderRadius:12,padding:10},dl:{fontSize:10,color:C.gray,fontWeight:"500",textTransform:"uppercase",letterSpacing:0.5},dv:{fontSize:14,fontWeight:"700",color:C.navy,marginTop:4}});

// ===== TSA =====
function TSA({nav}){
  var[ex,setEx]=useState(null),[tips,setTips]=useState(false),[rc,setRc]=useState(null),[rv,setRv]=useState(15),[done,setDone]=useState(false);
  function sub(){setDone(true);setTimeout(function(){setDone(false);setRc(null);setRv(15)},1500)}
  return <View style={ts.c}><StatusBar barStyle="light-content"/>
    <View style={ts.hd}><View style={{flexDirection:"row",justifyContent:"space-between",alignItems:"center",marginBottom:6,paddingTop:4}}><TouchableOpacity style={ts.bb} onPress={function(){nav("home")}}><Text style={{fontSize:16,color:C.white}}>{"\u2190"}</Text></TouchableOpacity><Text style={{fontSize:17,fontWeight:"700",color:C.white}}>TSA wait times</Text><View style={{width:36}}/></View><Text style={{fontSize:12,color:C.gold,fontWeight:"600",letterSpacing:1,textAlign:"center",marginBottom:6}}>{"KONT \u00b7 LIVE ESTIMATES"}</Text><Text style={{fontSize:11,color:"rgba(255,255,255,0.4)",textAlign:"center"}}>Crowd-sourced by ONT travelers</Text></View>
    <ScrollView style={{flex:1}}>
      <TouchableOpacity style={ts.tipH} onPress={function(){setTips(!tips)}}><View style={{flexDirection:"row",alignItems:"center",gap:8}}><View style={ts.tipI}><Text style={{fontSize:14}}>{"\ud83d\udca1"}</Text></View><Text style={{fontSize:14,fontWeight:"700",color:C.navy}}>Tips for faster screening</Text></View><Text style={{fontSize:16,color:C.gray}}>{tips?"\u25b4":"\u25be"}</Text></TouchableOpacity>
      {tips?<View style={ts.tipB}>{["Have boarding pass and ID ready","Remove laptops and liquids","Wear easy-to-remove shoes","Consider TSA PreCheck"].map(function(t,i){return <View key={i} style={ts.tipR}><View style={ts.tipBl}><Text style={{fontSize:11,fontWeight:"700",color:"#8b6914"}}>{i+1}</Text></View><Text style={{fontSize:13,color:C.navy}}>{t}</Text></View>})}</View>:null}
      <View style={ts.sum}><View style={ts.si}><Text style={ts.sml}>Avg. wait</Text><Text style={ts.smv}>{Math.round(TSA_CPS.reduce(function(a,c){return a+c.wait},0)/TSA_CPS.length)} min</Text></View><View style={ts.div}/><View style={ts.si}><Text style={ts.sml}>Reports</Text><Text style={ts.smv}>{TSA_CPS.reduce(function(a,c){return a+c.reports},0)}</Text></View><View style={ts.div}/><View style={ts.si}><Text style={ts.sml}>Best</Text><Text style={[ts.smv,{fontSize:14,color:"#0a7c4f"}]}>{TSA_CPS.reduce(function(a,c){return c.wait<a.wait?c:a}).name.replace("TSA ","")}</Text></View></View>
      <View style={{paddingHorizontal:16}}><Text style={ts.sl}>Checkpoints</Text>
        {TSA_CPS.map(function(cp){var o=ex===cp.id;return <View key={cp.id} style={ts.cpC}>
          <TouchableOpacity style={{flexDirection:"row",justifyContent:"space-between",alignItems:"center"}} onPress={function(){setEx(o?null:cp.id)}}>
            <View style={{flexDirection:"row",gap:12,alignItems:"center"}}><View style={[ts.wb,{backgroundColor:wb(cp.wait)}]}><Text style={{fontSize:18,fontWeight:"800",color:wc(cp.wait)}}>{cp.wait}</Text><Text style={{fontSize:9,fontWeight:"600",color:wc(cp.wait)}}>min</Text></View><View><Text style={{fontSize:15,fontWeight:"700",color:C.navy}}>{cp.name}</Text><View style={{flexDirection:"row",alignItems:"center",gap:6,marginTop:2}}><Text style={{fontSize:12,fontWeight:"600",color:wc(cp.wait)}}>{wl(cp.wait)}</Text></View></View></View>
            <Text style={{fontSize:18,color:C.gray}}>{o?"\u25b4":"\u25be"}</Text>
          </TouchableOpacity>
          {o?<View style={{marginTop:14,borderTopWidth:1,borderTopColor:C.grayLight,paddingTop:14}}><Text style={{fontSize:12,color:C.gray,marginBottom:10}}>{cp.location} {"\u00b7"} {cp.hours}</Text><View style={{flexDirection:"row",gap:8}}><View style={ts.mc}><Text style={{fontSize:10,color:C.gray}}>Reports</Text><Text style={{fontSize:13,fontWeight:"700",color:C.navy}}>{cp.reports}</Text></View><View style={ts.mc}><Text style={{fontSize:10,color:C.gray}}>Last report</Text><Text style={{fontSize:13,fontWeight:"700",color:C.navy}}>{cp.lastReport}</Text></View></View><View style={{flexDirection:"row",gap:6,marginTop:10}}>{cp.lanes.map(function(l){return <View key={l} style={ts.lp}><Text style={{fontSize:11,fontWeight:"500",color:"#8b6914"}}>{l}</Text></View>})}</View><View style={{flexDirection:"row",gap:8,marginTop:14}}><TouchableOpacity style={ts.rpb} onPress={function(){setRc(cp)}}><Text style={{fontSize:13,fontWeight:"600",color:C.navy}}>Report wait time</Text></TouchableOpacity><TouchableOpacity style={ts.nvb}><Text style={{fontSize:13,fontWeight:"700",color:C.gold}}>Navigate</Text></TouchableOpacity></View></View>:null}
        </View>})}
      </View><View style={{height:20}}/>
    </ScrollView>
    {rc?<TouchableOpacity style={ts.ov} activeOpacity={1} onPress={function(){setRc(null);setDone(false)}}>
      <View style={ts.sh}><View style={ts.handle}/>
        {done?<View style={{alignItems:"center",paddingVertical:20}}><View style={{width:56,height:56,borderRadius:28,backgroundColor:"#e6f9f0",alignItems:"center",justifyContent:"center",marginBottom:12}}><Text style={{fontSize:24}}>{"\u2713"}</Text></View><Text style={{fontSize:18,fontWeight:"700",color:C.navy}}>Thanks for reporting!</Text></View>
        :<View><Text style={{fontSize:18,fontWeight:"700",color:C.navy,marginBottom:4}}>Report wait time</Text><Text style={{fontSize:13,color:C.gray,marginBottom:20}}>{rc.name}</Text><Text style={{textAlign:"center",fontSize:48,fontWeight:"800",color:wc(rv)}}>{rv}<Text style={{fontSize:18,fontWeight:"600",color:C.gray}}> min</Text></Text><View style={{alignItems:"center",marginVertical:12}}><View style={{paddingVertical:5,paddingHorizontal:16,borderRadius:20,backgroundColor:wb(rv)}}><Text style={{fontSize:13,fontWeight:"600",color:wc(rv)}}>{wl(rv)}</Text></View></View><View style={{flexDirection:"row",gap:6,marginBottom:16}}>{[5,10,15,20,30,45].map(function(v){return <TouchableOpacity key={v} style={[ts.qb,rv===v&&{backgroundColor:C.navy,borderColor:C.navy}]} onPress={function(){setRv(v)}}><Text style={[{fontSize:12,fontWeight:"600",color:C.navy},rv===v&&{color:C.gold}]}>{v}m</Text></TouchableOpacity>})}</View><View style={{flexDirection:"row",gap:8}}><TouchableOpacity style={{flex:1,paddingVertical:12,borderRadius:12,borderWidth:1.5,borderColor:C.grayLight,alignItems:"center"}} onPress={function(){setRc(null)}}><Text style={{fontSize:14,fontWeight:"600",color:C.navy}}>Cancel</Text></TouchableOpacity><TouchableOpacity style={{flex:1,paddingVertical:12,borderRadius:12,backgroundColor:C.navy,alignItems:"center"}} onPress={sub}><Text style={{fontSize:14,fontWeight:"700",color:C.gold}}>Submit report</Text></TouchableOpacity></View></View>}
      </View>
    </TouchableOpacity>:null}
    <BT active="home" nav={nav}/>
  </View>;
}
var ts=StyleSheet.create({c:{flex:1,backgroundColor:C.bg},hd:{backgroundColor:C.navy,padding:16,paddingTop:10,borderBottomLeftRadius:20,borderBottomRightRadius:20,zIndex:10},bb:{width:36,height:36,borderRadius:10,backgroundColor:"rgba(255,255,255,0.08)",alignItems:"center",justifyContent:"center"},tipH:{flexDirection:"row",justifyContent:"space-between",alignItems:"center",backgroundColor:C.white,borderRadius:14,padding:12,marginHorizontal:16,marginTop:14,elevation:1},tipI:{width:28,height:28,borderRadius:8,backgroundColor:C.goldBg,alignItems:"center",justifyContent:"center"},tipB:{backgroundColor:C.white,borderBottomLeftRadius:14,borderBottomRightRadius:14,paddingHorizontal:14,paddingBottom:14,marginHorizontal:16,marginTop:-4},tipR:{flexDirection:"row",alignItems:"center",gap:10,marginBottom:8},tipBl:{width:22,height:22,borderRadius:11,backgroundColor:C.goldBg,alignItems:"center",justifyContent:"center"},sum:{flexDirection:"row",justifyContent:"space-around",alignItems:"center",backgroundColor:C.white,marginHorizontal:16,marginTop:12,borderRadius:16,paddingVertical:14,paddingHorizontal:8,elevation:1},si:{alignItems:"center",gap:2},sml:{fontSize:11,color:C.gray},smv:{fontSize:20,fontWeight:"800",color:C.navy},div:{width:1,height:32,backgroundColor:C.grayLight},sl:{fontSize:11,fontWeight:"700",color:C.gray,textTransform:"uppercase",letterSpacing:1.2,marginTop:20,marginBottom:10},cpC:{backgroundColor:C.white,borderRadius:18,padding:16,marginBottom:10,elevation:1},wb:{width:48,height:48,borderRadius:14,alignItems:"center",justifyContent:"center"},mc:{flex:1,padding:8,backgroundColor:C.bg,borderRadius:10,gap:2},lp:{paddingVertical:4,paddingHorizontal:10,borderRadius:20,backgroundColor:C.goldBg},rpb:{flex:1,paddingVertical:10,borderRadius:12,borderWidth:1.5,borderColor:C.grayLight,alignItems:"center"},nvb:{flex:1,paddingVertical:10,borderRadius:12,backgroundColor:C.navy,alignItems:"center"},ov:{position:"absolute",top:0,left:0,right:0,bottom:0,backgroundColor:"rgba(12,27,46,0.5)",justifyContent:"flex-end",zIndex:50},sh:{backgroundColor:C.white,borderTopLeftRadius:22,borderTopRightRadius:22,padding:20,paddingBottom:28},handle:{width:36,height:4,borderRadius:2,backgroundColor:C.grayLight,alignSelf:"center",marginBottom:14},qb:{flex:1,paddingVertical:8,borderRadius:10,borderWidth:1.5,borderColor:C.grayLight,alignItems:"center"}});

// ===== PROFILE =====
function Profile({nav}){
  var[sp,setSp]=useState(null);

  if(sp==="rewards")return <View style={pf.c}><View style={pf.sh}><TouchableOpacity style={pf.bb} onPress={function(){setSp(null)}}><Text style={{fontSize:16,color:C.white}}>{"\u2190"}</Text></TouchableOpacity><Text style={{fontSize:17,fontWeight:"700",color:C.white}}>ONT Rewards</Text><View style={{width:36}}/></View><ScrollView style={{flex:1}}><View style={{backgroundColor:C.navy,padding:24,alignItems:"center"}}><Text style={{fontSize:48,fontWeight:"800",color:C.gold}}>340</Text><Text style={{fontSize:14,color:"rgba(255,255,255,0.5)",marginTop:2}}>total points</Text><View style={pf.pb}><View style={[pf.pf,{width:"57%"}]}/></View><View style={{flexDirection:"row",justifyContent:"space-between",width:"100%",marginTop:6}}><Text style={{fontSize:11,color:"rgba(255,255,255,0.4)"}}>260 pts to next reward</Text><Text style={{fontSize:11,color:C.gold}}>600 pts</Text></View></View><View style={{padding:16}}><Text style={pf.sl}>Rewards available</Text>{[{n:"Free side item",p:"60 pts",i:"\ud83c\udf5f"},{n:"Free drink",p:"60 pts",i:"\ud83e\udd64"},{n:"$5 off next order",p:"120 pts",i:"\ud83d\udcb0"}].map(function(r){return <View key={r.n} style={pf.rwR}><View style={{flexDirection:"row",alignItems:"center",gap:12}}><View style={pf.rwI}><Text style={{fontSize:18}}>{r.i}</Text></View><View><Text style={{fontSize:14,fontWeight:"600",color:C.navy}}>{r.n}</Text><Text style={{fontSize:12,color:C.gray}}>{r.p}</Text></View></View><TouchableOpacity style={pf.rdB}><Text style={{fontSize:12,fontWeight:"700",color:C.gold}}>Redeem</Text></TouchableOpacity></View>})}</View></ScrollView></View>;

  if(sp==="orders")return <View style={pf.c}><View style={pf.sh}><TouchableOpacity style={pf.bb} onPress={function(){setSp(null)}}><Text style={{fontSize:16,color:C.white}}>{"\u2190"}</Text></TouchableOpacity><Text style={{fontSize:17,fontWeight:"700",color:C.white}}>Order history</Text><View style={{width:36}}/></View><ScrollView style={{flex:1,padding:16}}>{[{p:"Starbucks",it:"Iced Latte, Croissant",d:"Mar 18, 2026",t:"$9.45",i:"\u2615"},{p:"El Pollo Loco",it:"Chicken Bowl",d:"Mar 12, 2026",t:"$14.20",i:"\ud83c\udf57"},{p:"Hudson News",it:"Water, Trail Mix",d:"Feb 28, 2026",t:"$18.75",i:"\ud83d\udecd"}].map(function(o){return <View key={o.p+o.d} style={pf.oC}><View style={{flexDirection:"row",gap:12}}><View style={pf.oI}><Text style={{fontSize:18}}>{o.i}</Text></View><View style={{flex:1}}><View style={{flexDirection:"row",justifyContent:"space-between"}}><Text style={{fontSize:14,fontWeight:"700",color:C.navy}}>{o.p}</Text><Text style={{fontSize:13,fontWeight:"700",color:C.navy}}>{o.t}</Text></View><Text style={{fontSize:12,color:C.gray,marginTop:2}}>{o.it}</Text><View style={{flexDirection:"row",justifyContent:"space-between",marginTop:6}}><Text style={{fontSize:11,color:C.gray}}>{o.d}</Text><View style={{backgroundColor:"#e6f9f0",paddingHorizontal:8,paddingVertical:2,borderRadius:6}}><Text style={{fontSize:11,fontWeight:"600",color:"#0a7c4f"}}>Completed</Text></View></View></View></View><View style={{flexDirection:"row",gap:8,marginTop:12}}><TouchableOpacity style={pf.abf}><Text style={{fontSize:12,fontWeight:"700",color:C.gold}}>Reorder</Text></TouchableOpacity><TouchableOpacity style={pf.abo}><Text style={{fontSize:12,fontWeight:"600",color:C.navy}}>Receipt</Text></TouchableOpacity></View></View>})}</ScrollView></View>;

  if(sp==="settings")return <View style={pf.c}><View style={pf.sh}><TouchableOpacity style={pf.bb} onPress={function(){setSp(null)}}><Text style={{fontSize:16,color:C.white}}>{"\u2190"}</Text></TouchableOpacity><Text style={{fontSize:17,fontWeight:"700",color:C.white}}>Settings</Text><View style={{width:36}}/></View><ScrollView style={{flex:1,padding:16}}><Text style={pf.sl}>Account</Text><View style={pf.card}>{["Edit profile","Change password","Linked accounts"].map(function(l,i,a){return <View key={l} style={[pf.sRow,i===a.length-1&&{borderBottomWidth:0}]}><Text style={{fontSize:14,fontWeight:"600",color:C.navy}}>{l}</Text><Text style={{fontSize:16,color:C.grayLight}}>{"\u203a"}</Text></View>})}</View><Text style={pf.sl}>App preferences</Text><View style={pf.card}>{[{l:"Language",v:"English"},{l:"Distance units",v:"Feet / Miles"},{l:"Map theme",v:"Light"}].map(function(p,i,a){return <View key={p.l} style={[pf.sRow,i===a.length-1&&{borderBottomWidth:0}]}><Text style={{fontSize:14,fontWeight:"600",color:C.navy}}>{p.l}</Text><View style={{flexDirection:"row",alignItems:"center",gap:6}}><Text style={{fontSize:13,color:C.gray}}>{p.v}</Text><Text style={{fontSize:16,color:C.grayLight}}>{"\u203a"}</Text></View></View>})}</View><Text style={{textAlign:"center",marginTop:20,fontSize:11,color:"#ccc"}}>ONT Navigator v1.1</Text></ScrollView></View>;

  return <View style={pf.c}><StatusBar barStyle="light-content"/>
    <View style={{backgroundColor:C.navy,padding:16,paddingTop:10}}>
      <View style={{flexDirection:"row",justifyContent:"space-between",alignItems:"center",paddingTop:4}}><TouchableOpacity style={pf.bb} onPress={function(){nav("home")}}><Text style={{fontSize:16,color:C.white}}>{"\u2190"}</Text></TouchableOpacity><Text style={{fontSize:17,fontWeight:"700",color:C.white}}>Profile</Text><View style={{width:36}}/></View>
      <View style={{alignItems:"center",paddingBottom:18,paddingTop:8}}><View style={pf.av}><Text style={{fontSize:28,color:C.gold,fontWeight:"700"}}>PF</Text></View><Text style={{fontSize:20,fontWeight:"800",color:C.white,marginTop:10}}>Patrick Fong</Text><Text style={{fontSize:12,color:"rgba(255,255,255,0.45)",marginTop:4}}>pfong001@email.com</Text></View>
    </View>
    <ScrollView style={{flex:1}}>
      <View style={{flexDirection:"row",gap:8,padding:16,paddingBottom:0}}>{[{n:"340",l:"Pts"},{n:"12",l:"Flights"},{n:"4",l:"Orders"}].map(function(s){return <TouchableOpacity key={s.l} style={pf.stat} onPress={function(){if(s.l==="Pts")setSp("rewards");if(s.l==="Orders")setSp("orders")}}><Text style={{fontSize:22,fontWeight:"800",color:C.navy}}>{s.n}</Text><Text style={{fontSize:10,color:C.gray,marginTop:2}}>{s.l}</Text></TouchableOpacity>})}</View>
      <View style={{padding:16,paddingTop:12}}>
        {[{ic:"\ud83c\udfc6",l:"Rewards",s:"340 points",p:"rewards"},{ic:"\ud83d\uded2",l:"Order history",s:"Starbucks \u00b7 $9.45",p:"orders",ct:2},{ic:"\ud83d\udcb3",l:"Saved cards",s:"3 cards linked",p:"wallet"},{ic:"\u2708",l:"Travel preferences",s:"ONT \u00b7 Southwest",p:"prefs"},{ic:"\u2699",l:"Settings",s:"Account, privacy, notifications",p:"settings"}].map(function(item){return <TouchableOpacity key={item.l} style={pf.mRow} onPress={function(){setSp(item.p)}}><View style={{flexDirection:"row",alignItems:"center",gap:14}}><View style={pf.mIc}><Text style={{fontSize:18}}>{item.ic}</Text></View><View><View style={{flexDirection:"row",alignItems:"center",gap:8}}><Text style={{fontSize:15,fontWeight:"600",color:C.navy}}>{item.l}</Text>{item.ct?<View style={{backgroundColor:C.gold,borderRadius:10,paddingHorizontal:7,paddingVertical:2}}><Text style={{fontSize:10,fontWeight:"700",color:C.white}}>{item.ct}</Text></View>:null}</View><Text style={{fontSize:12,color:C.gray,marginTop:1}}>{item.s}</Text></View></View><Text style={{fontSize:16,color:C.grayLight}}>{"\u203a"}</Text></TouchableOpacity>})}
      </View>
      <View style={{padding:16,paddingTop:0}}><TouchableOpacity style={pf.soB}><Text style={{fontSize:15,fontWeight:"600",color:"#e05555",textAlign:"center"}}>Sign out</Text></TouchableOpacity><Text style={{textAlign:"center",marginTop:12,fontSize:11,color:"#ccc"}}>ONT Navigator v1.1 {"\u00b7"} KONT</Text></View>
    </ScrollView>
    <BT active="profile" nav={nav}/>
  </View>;
}
var pf=StyleSheet.create({c:{flex:1,backgroundColor:C.bg},sh:{backgroundColor:C.navy,padding:16,paddingTop:10,flexDirection:"row",justifyContent:"space-between",alignItems:"center"},bb:{width:36,height:36,borderRadius:10,backgroundColor:"rgba(255,255,255,0.08)",alignItems:"center",justifyContent:"center"},av:{width:72,height:72,borderRadius:36,backgroundColor:"rgba(201,168,76,0.1)",borderWidth:2.5,borderColor:"rgba(201,168,76,0.25)",alignItems:"center",justifyContent:"center"},stat:{flex:1,backgroundColor:C.white,borderRadius:14,paddingVertical:12,alignItems:"center",elevation:1},mRow:{flexDirection:"row",justifyContent:"space-between",alignItems:"center",padding:14,backgroundColor:C.white,borderRadius:14,marginBottom:6,elevation:1},mIc:{width:40,height:40,borderRadius:12,backgroundColor:C.goldBg,alignItems:"center",justifyContent:"center"},sl:{fontSize:11,fontWeight:"700",color:C.gray,textTransform:"uppercase",letterSpacing:1.2,marginTop:18,marginBottom:10},card:{backgroundColor:C.white,borderRadius:14,paddingHorizontal:14,elevation:1},sRow:{flexDirection:"row",justifyContent:"space-between",alignItems:"center",paddingVertical:14,borderBottomWidth:1,borderBottomColor:C.grayLight},pb:{width:"100%",height:6,borderRadius:3,backgroundColor:"rgba(255,255,255,0.1)",marginTop:16},pf:{height:6,borderRadius:3,backgroundColor:C.gold},rwR:{flexDirection:"row",justifyContent:"space-between",alignItems:"center",paddingVertical:12,borderBottomWidth:1,borderBottomColor:C.grayLight},rwI:{width:40,height:40,borderRadius:12,backgroundColor:C.goldBg,alignItems:"center",justifyContent:"center"},rdB:{paddingVertical:6,paddingHorizontal:14,borderRadius:8,backgroundColor:C.navy},oC:{backgroundColor:C.white,borderRadius:14,padding:14,marginBottom:8,elevation:1},oI:{width:42,height:42,borderRadius:12,backgroundColor:C.goldBg,alignItems:"center",justifyContent:"center"},abf:{flex:1,paddingVertical:8,borderRadius:10,backgroundColor:C.navy,alignItems:"center"},abo:{flex:1,paddingVertical:8,borderRadius:10,borderWidth:1.5,borderColor:C.grayLight,alignItems:"center"},soB:{width:"100%",paddingVertical:14,borderRadius:14,borderWidth:1.5,borderColor:"#e05555"}});

// ===== APP ROOT =====
export default function App(){
  var[w,setW]=useState(true),[sc,setSc]=useState("home");
  if(w)return <Welcome done={function(){setW(false)}}/>;
  switch(sc){
    case"home":return <Home nav={setSc}/>;
    case"map":return <MapScreen nav={setSc}/>;
    case"flights":return <Flights nav={setSc}/>;
    case"tsa":return <TSA nav={setSc}/>;
    case"profile":return <Profile nav={setSc}/>;
    default:return <Home nav={setSc}/>;
  }
}